#!/usr/bin/env bash
#Write a Bash script that displays numbers from 1 to 100. Requirements:Displays FizzBuzz when the number is a multiple of 3 and 5, Displays Fizz when the number is multiple of 3, Displays Buzz when the number is a multiple of 5, Otherwise, displays the number, In a list format.

count=1
for num in {1..100}; do

    if (( num % 3 == 0 )); then
	echo "Fizz"
    elif (( num % 5 == 0 )); then
	echo "Buzz"
    elif (( num % 15 == 0)); then
	echo "FizzBuzz"
    else
	echo "$num"
    fi

done
