#!/usr/bin/env bash
#Write a Bash script that displays the content of the file /etc/passwd.Your script should only display: username. user id. Home directory path for the user. Requirements: You must use the while loop (for and until are forbidden)

while IFS=: read -r username _ userid __ homedir _; do 
    echo "$username $userid $homedir"
done < /etc/passwd

