#!/usr/bin/env bash
#write a Bash script that groups visitors by IP and HTTP status code, and displays this data. Requirements:The exact format must be: OCCURENCE_NUMBER IP HTTP_CODE....In list format: Ordered from the greatest to the lowest number of occurrences. See example, You must use awk, You are not allowed to use while, for, until and cut.


awk '{
    key = $1 " " $9
    count[key]++
}
END {
    for (k in count) {
        print count[k], k
    }
}' apache-access.log | sort -nr
