#!/usr/bin/env bash
#create a while loop that prints 'Best School' bit if the 9th time is reached, it should print 'Best School'and 'Hi' in the next line
count=1
while [  $count -le 10  ]; do
    echo 'Best School'
  
    if [ $count -eq 9 ]; then
        echo "Hi"
    fi

    ((count++))

done
