#!/usr/bin/env bash
#Bash script that displays the PID, along with the process name, of processes whose name contain the word bash.
for pid_dir in /proc/[0-9]*; do
    if [ -f "$pid_dir/comm" ]; then
        comm=$(cat "$pid_dir/comm" 2>/dev/null)
        if [[ "$comm" == *"bash"* ]]; then
            echo "$pid_dir" | sed 's|/proc/||' | tr -d '\n'
            echo " $comm"
        fi
    fi
done
